add RTR job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -921,3 +921,14 @@ jobs:
         with:
           name: ${{ steps.process.outputs.artifactName }}
           path: ${{ steps.process.outputs.artifactPath }}
+
+  job_ready_to_release:
+    name: Ready to release
+    needs: [job_required_tests, job_artifacts, job_size_check, job_lint, job_circular_dep_check]
+    if: needs.job_get_metadata.outputs.is_release == 'true'
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Check for failures
+        if: contains(needs.*.result, 'failure')
+        run: |
+          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
